//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BangbooMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangbooSupplyDetail
    {
        public int ID_Detail { get; set; }
        public int ID_Bangboo { get; set; }
        public int ID_Supplier { get; set; }
        public int SupplyAmount { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
        public Nullable<int> UnitCost { get; set; }
    
        public virtual Bangboo Bangboo { get; set; }
        public virtual BangbooSupplier BangbooSupplier { get; set; }
    }
}
