//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BangbooMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BangbooNETEntities : DbContext
    {
        public BangbooNETEntities()
            : base("name=BangbooNETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Bangboo> Bangboos { get; set; }
        public virtual DbSet<BangbooSale> BangbooSales { get; set; }
        public virtual DbSet<BangbooSupplier> BangbooSuppliers { get; set; }
        public virtual DbSet<BangbooSupplyDetail> BangbooSupplyDetails { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<SalesReceipt> SalesReceipts { get; set; }
    }
}
