//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BangbooMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesReceipt()
        {
            this.BangbooSales = new HashSet<BangbooSale>();
        }
    
        public int ID_Sale { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public int Employee_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangbooSale> BangbooSales { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
